sudo: false
language: ruby
before_install: gem install bundler -v 1.15.4

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - ruby-head
  - jruby-9.1.16.0
  - jruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.16.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.3.7
      gemfile: gemfiles/rails_edge.gemfile
